CREATE TABLE IF NOT EXISTS EMPLOYEE_DB.HR.GITHUB_ACTIONS_TEST (
    TEST_ID INTEGER,
    TEST_MESSAGE VARCHAR(200),
    CREATED_AT TIMESTAMP
);

INSERT INTO EMPLOYEE_DB.HR.GITHUB_ACTIONS_TEST
(
    TEST_ID,
    TEST_MESSAGE,
    CREATED_AT
)
VALUES
(
    1,
    'Deployed automatically from GitHub Actions',
    CURRENT_TIMESTAMP()
);