-- Step 1: Create database and schema
CREATE DATABASE IF NOT EXISTS EMPLOYEE_DB;

CREATE SCHEMA IF NOT EXISTS EMPLOYEE_DB.HR;

-- Step 2: Create employee table
CREATE OR REPLACE TABLE EMPLOYEE_DB.HR.EMPLOYEES (
    EMPLOYEE_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
	LOCATION VARCHAR(100),
    HIRE_DATE DATE,
    JOB_TITLE VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2),
    MANAGER_ID INT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);