-- Step 4: Create employee view

CREATE OR REPLACE VIEW EMPLOYEE_DB.HR.VW_EMPLOYEES AS
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    JOB_TITLE,
    DEPARTMENT,
    SALARY,
    MANAGER_ID,
    IS_ACTIVE
FROM EMPLOYEE_DB.HR.EMPLOYEES;