-- Populate employee location

UPDATE EMPLOYEE_DB.HR.EMPLOYEES
SET LOCATION =
    CASE
        WHEN EMPLOYEE_ID BETWEEN 1 AND 20 THEN 'Bangalore'
        WHEN EMPLOYEE_ID BETWEEN 21 AND 40 THEN 'Hyderabad'
        WHEN EMPLOYEE_ID BETWEEN 41 AND 60 THEN 'Chennai'
        WHEN EMPLOYEE_ID BETWEEN 61 AND 80 THEN 'Pune'
        WHEN EMPLOYEE_ID BETWEEN 81 AND 100 THEN 'Mumbai'
    END
WHERE EMPLOYEE_ID BETWEEN 1 AND 100;